baseURL = "/"
languageCode = "en-us"
title = "TANXY'S CLUB"
theme = "hugo-paper"
pygmentsCodefences = true

[params]
    githubProfile = "https://github.com/tan35"
    sources = "https://tanxy.tplog.io"
    dateForm = "2006-01-02"
    author = "Tan35"
    homeTypes = "posts, tutorials"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = -100
    [[menu.main]]
        name = "Tutorials"
        url = "/tutorials/"
        weight = -90
    [[menu.main]]
        name = "Reported bugs"
        url = "/bugs/"
        weight = -80
    [[menu.main]]
        name = "Reviews"
        url = "/reviews/"
        weight = -70